### ISSUE TITLE
Is this a confirmed-working algorithm

### ISSUE THREAD

**Issue by JohnAD** [nivshalomlom/Negamax-Framework#1]
I wrote a non-recursive version of the negamax algo long ago in Python in a library called [Easy AI ](https://github.com/Zulko/easyAI/blob/master/easyAI/AI/NonRecursiveNegamax.py) and have recently translated it to C#. But, I'm having trouble getting the bugs out. The non-recursive version does not just have border-cases to watch out for. It is pretty much nothing BUT border cases. (It uses a "sliding" array to track progress through the tree.)

I saw your repo in a GitHub search and am interested in using it to second-check and debug my C# algorithm. Yours is recursive in nature, but that is okay. I just want to make sure I'm getting the same output from both your and my algorithms. But before I do that I figured I'd ask: is this algorithm fairly well debugged with real-world use?

**Comment by nivshalomlom** [comment]
Hey John, I tested this code with a few games like checkers and chess a while back, it seemed to work well with the heuristics I used, gl with your testing!
